spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-server
    username: postgres
    password: ali.1381
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create